# Generated by Django 5.0.4 on 2024-04-26 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=False)),
                ('team_phone', models.CharField(max_length=255)),
                ('team_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has completed the email verification process to allow login.', verbose_name='verified')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_nurse', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('fullname', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=255)),
                ('circurmstance', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='ctrlApi.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_specialization', models.CharField(choices=[('Cardiologist: Specializes in diagnosing and treating diseases related to the heart and blood vessels. ', 'Specializes in diagnosing and treating diseases related to the heart and blood vessels.'), ('Neurologist: Deals with disorders of the nervous system, including the brain, spinal cord, and nerves. ', 'Deals with disorders of the nervous system, including the brain, spinal cord, and nerves.'), ('Oncologist: Focuses on the diagnosis and treatment of cancer. ', 'Focuses on the diagnosis and treatment of cancer.'), ('Orthopedic Surgeon: Specializes in treating musculoskeletal injuries and disorders, including bones, joints, ligaments, tendons, and muscles. ', 'Specializes in treating musculoskeletal injuries and disorders, including bones, joints, ligaments, tendons, and muscles.'), ('Pediatrician: Provides medical care for infants, children, and adolescents. ', 'Provides medical care for infants, children, and adolescents.'), ('Gynecologist/Obstetrician (OB/GYN): Deals with the female reproductive system, providing care for women during pregnancy, childbirth, and postpartum. ', 'Deals with the female reproductive system, providing care for women during pregnancy, childbirth, and postpartum.'), ('Dermatologist: Specializes in diagnosing and treating conditions related to the skin, hair, and nails. ', 'Specializes in diagnosing and treating conditions related to the skin, hair, and nails.'), ('Endocrinologist: Focuses on disorders of the endocrine system, including hormones and glands such as the thyroid, pancreas, and adrenal glands. ', 'Focuses on disorders of the endocrine system, including hormones and glands such as the thyroid, pancreas, and adrenal glands.'), ('Gastroenterologist: Deals with diseases and disorders of the digestive system, including the stomach, intestines, liver, and pancreas. ', 'Deals with diseases and disorders of the digestive system, including the stomach, intestines, liver, and pancreas.'), ('Pulmonologist: Specializes in diseases of the respiratory system, including the lungs and airways. ', 'Specializes in diseases of the respiratory system, including the lungs and airways.'), ('Urologist: Focuses on diseases and disorders of the urinary tract and male reproductive system. ', 'Focuses on diseases and disorders of the urinary tract and male reproductive system.'), ('Rheumatologist: Deals with autoimmune and musculoskeletal disorders, such as arthritis. ', 'Deals with autoimmune and musculoskeletal disorders, such as arthritis.'), ('Psychiatrist: Specializes in diagnosing and treating mental health disorders. ', 'Specializes in diagnosing and treating mental health disorders.'), ('Anesthesiologist: Administers anesthesia and monitors patients during surgery and other medical procedures. ', 'Administers anesthesia and monitors patients during surgery and other medical procedures.'), ('Radiologist: Interprets medical imaging tests such as X-rays, CT scans, MRIs, and ultrasounds. ', 'Interprets medical imaging tests such as X-rays, CT scans, MRIs, and ultrasounds.'), ('Ophthalmologist: Deals with diseases and disorders of the eye, providing medical and surgical care. ', 'Deals with diseases and disorders of the eye, providing medical and surgical care.'), ('Neonatologist: Specializes in the care of newborn infants, particularly those who are premature or have health complications. ', 'Specializes in the care of newborn infants, particularly those who are premature or have health complications.'), ('Nephrologist: Focuses on diseases and disorders of the kidneys. ', 'Focuses on diseases and disorders of the kidneys.'), ('Allergist/Immunologist: Specializes in diagnosing and treating allergies and immune system disorders. ', 'Specializes in diagnosing and treating allergies and immune system disorders.'), ('Geriatrician: Provides medical care for elderly patients, addressing age-related health concerns and promoting healthy aging. ', 'Provides medical care for elderly patients, addressing age-related health concerns and promoting healthy aging.'), ('Intensivist: Specializes in caring for critically ill patients in the intensive care unit (ICU). ', 'Specializes in caring for critically ill patients in the intensive care unit (ICU).'), ('Hematologist: Focuses on diseases and disorders of the blood, including leukemia, anemia, and clotting disorders. ', 'Focuses on diseases and disorders of the blood, including leukemia, anemia, and clotting disorders.'), ('Infectious Disease Specialist: Deals with the diagnosis and treatment of infectious diseases caused by bacteria, viruses, fungi, or parasites. ', 'Deals with the diagnosis and treatment of infectious diseases caused by bacteria, viruses, fungi, or parasites.'), ('Pain Management Specialist: Specializes in diagnosing and treating chronic pain conditions, using a variety of techniques including medications, physical therapy, and interventional procedures. ', 'Specializes in diagnosing and treating chronic pain conditions, using a variety of techniques including medications, physical therapy, and interventional procedures.'), ('Sports Medicine Physician: Provides medical care for athletes and individuals with sports-related injuries, focusing on prevention, diagnosis, and treatment. ', 'Provides medical care for athletes and individuals with sports-related injuries, focusing on prevention, diagnosis, and treatment.'), ('Sleep Medicine Specialist: Deals with disorders related to sleep, such as insomnia, sleep apnea, and narcolepsy. ', 'Deals with disorders related to sleep, such as insomnia, sleep apnea, and narcolepsy.'), ('Plastic Surgeon: Specializes in cosmetic and reconstructive surgery to improve the appearance or function of body structures. ', 'Specializes in cosmetic and reconstructive surgery to improve the appearance or function of body structures.'), ('ENT Specialist (Otolaryngologist): Deals with disorders of the ear, nose, and throat, including hearing loss, sinusitis, and throat infections. ', 'Deals with disorders of the ear, nose, and throat, including hearing loss, sinusitis, and throat infections.'), ('Physiatrist (Physical Medicine and Rehabilitation Physician): Focuses on restoring function and improving quality of life for patients with physical disabilities or injuries. ', 'Focuses on restoring function and improving quality of life for patients with physical disabilities or injuries.'), ('Geneticist: Specializes in diagnosing and managing genetic disorders and providing genetic counseling to patients and families. ', 'Specializes in diagnosing and managing genetic disorders and providing genetic counseling to patients and families.'), ('Palliative Care Physician: Focuses on relieving pain and managing symptoms for patients with serious illnesses, aiming to improve quality of life and provide support for patients and their families. ', 'Focuses on relieving pain and managing symptoms for patients with serious illnesses, aiming to improve quality of life and provide support for patients and their families.'), ('Addiction Medicine Specialist: Deals with the prevention, diagnosis, and treatment of substance abuse and addiction disorders. ', 'Deals with the prevention, diagnosis, and treatment of substance abuse and addiction disorders.'), ('Clinical Genetic Counselor: Provides counseling and support to individuals and families at risk for inherited genetic conditions. ', 'Provides counseling and support to individuals and families at risk for inherited genetic conditions.'), ('Reproductive Endocrinologist: Specializes in fertility and reproductive health, providing treatments for infertility and hormonal disorders affecting fertility. ', 'Specializes in fertility and reproductive health, providing treatments for infertility and hormonal disorders affecting fertility.'), ('Interventional Radiologist: Performs minimally invasive procedures using medical imaging techniques to diagnose and treat various conditions, such as placing stents or performing biopsies. ', 'Performs minimally invasive procedures using medical imaging techniques to diagnose and treat various conditions, such as placing stents or performing biopsies.'), ('Forensic Pathologist: Investigates the cause of death in cases of suspicious or sudden deaths, often working with law enforcement agencies. ', 'Investigates the cause of death in cases of suspicious or sudden deaths, often working with law enforcement agencies.'), ('Wound Care Specialist: Focuses on the treatment and management of complex wounds, such as diabetic ulcers, pressure sores, and surgical wounds. ', 'Focuses on the treatment and management of complex wounds, such as diabetic ulcers, pressure sores, and surgical wounds.'), ('Telemedicine Specialist: Provides medical care remotely through telecommunication technologies, offering consultations, diagnoses, and treatment plans over video calls or other virtual platforms. ', 'Provides medical care remotely through telecommunication technologies, offering consultations, diagnoses, and treatment plans over video calls or other virtual platforms.'), ('Occupational Medicine Physician: Focuses on the prevention and management of work-related injuries and illnesses, as well as promoting workplace health and safety. ', 'Focuses on the prevention and management of work-related injuries and illnesses, as well as promoting workplace health and safety.'), ('Adolescent Medicine Specialist: Provides medical care specifically tailored to the unique health needs of adolescents and young adults, addressing physical, emotional, and social aspects of health and development. ', 'Provides medical care specifically tailored to the unique health needs of adolescents and young adults, addressing physical, emotional, and social aspects of health and development.')], max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('banner', models.ImageField(upload_to='upload/banner')),
                ('logo', models.ImageField(upload_to='upload/logo')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Nurce_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='upload/Doctor_nurse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stafforganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stafforganization', to='ctrlApi.organization')),
            ],
        ),
        migrations.AddField(
            model_name='ambulance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulance', to='ctrlApi.organization'),
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=255)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorce', 'Divorce')], max_length=255)),
                ('street_addresss', models.CharField(max_length=255)),
                ('street_addresss2', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_zipcode', models.CharField(max_length=255)),
                ('requestor_PhoneNumber', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('health_insurance', models.TextField(verbose_name='Health Insurance')),
                ('medical_Condition', models.TextField(max_length=255, verbose_name='Patient Medical Condition/History')),
                ('medical_referals', models.TextField(max_length=255)),
                ('appointment_status_urgency', models.CharField(choices=[('Routine check-up', 'Routine check-up'), ('Non-urgent medical check-up', 'Non-urgent medical check-up'), ('Surgical Appointment', 'Surgical Appointment'), ('Urgent medical check-up', 'Urgent medical check-up')], max_length=255)),
                ('preferred_days_of_appointment', models.CharField(choices=[('Any day', 'Any day'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=255)),
                ('time_of_appointment', models.DateTimeField()),
                ('alternative_time_of_appointment', models.DateTimeField()),
                ('appointments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ctrlApi.organization')),
                ('staffspatients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffspatients', to='ctrlApi.doctor_nurce_profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='upload/Doctor_nurse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
